### ISSUE TITLE
rails master warning

### ISSUE THREAD

**Issue by masterkain** [mperham/girl_friday#39]
```
:public is no longer used to avoid overloading Module#public, use :public_folder instead
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/girl_friday-dbd3c7f9cade/lib/girl_friday/server.rb:17:in `<class:Server>'
```

**Comment by mperham** [comment]
So if I change this to public_folder, would that break people who are using an older version of the Sinatra gem?

**Comment by mperham** [comment]
I'll just update the dep to require ~> 1.3

**Comment by rkh** [comment]
Yes, `:public_folder` will only work in Sinatra >= 1.2.7 (we're at 1.3.1 atm). In >= 1.3.0 you will not be able to read the value via `settings.public`, which is why it's important for us to display that warning.

Here is what you can do if you don't want to check the Sinatra version:

``` ruby
set(:public_folder, ...)
set(:public) { public_folder) if settings.respond_to? :public
```

If you don't mind the warning, you can just leave it at `set(:public, ...)`

I'm truly sorry for the inconvenience, but overriding `#public` really messed with some Ruby code.

**Comment by mperham** [comment]
If someone is looking for OSS work, it would be nice to have an integration test or two for the gf server functionality.  That's completely untested right now.  :-(
